# Generated by Django 4.2.2 on 2024-08-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="lms/course_img", verbose_name="превью"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="lesson_video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="lms/lesson_video",
                verbose_name="видео урока",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="lms/lesson_img", verbose_name="превью"
            ),
        ),
    ]
